{{- if not .Values.hub.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pandar.hubDatabaseSecretName" . }}
  labels:
    {{- include "pandar.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
type: Opaque
data:
  PANDAR_DATABASE_URL: {{ .Values.hub.database.url | b64enc | quote }}
{{- end }}
