apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pandar.fullname" . }}-hub
  labels:
    {{- include "pandar.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
data:
  PANDAR_HUB_BIND: {{ printf "0.0.0.0:%v" .Values.hub.service.httpPort | quote }}
  PANDAR_HUB_GRPC_BIND: {{ printf "0.0.0.0:%v" .Values.hub.service.grpcPort | quote }}
  {{- range $name, $value := .Values.hub.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
