#pragma once

namespace Slic3r { class BBLModelTask; }

#if defined(_WIN32)
#define PANDAR_STUDIO_FT_CALL __cdecl
#else
#define PANDAR_STUDIO_FT_CALL
#endif

#if defined(PANDAR_STUDIO_BIND_MODEL_ARGUMENT)
#define PANDAR_STUDIO_BIND_MODEL_PARAMETER std::string,
#else
#define PANDAR_STUDIO_BIND_MODEL_PARAMETER
#endif

#ifndef PANDAR_STUDIO_EXPORT
#define PANDAR_STUDIO_EXPORT(name, target, result, parameters) PANDAR_ABI result name parameters;
#define PANDAR_STUDIO_EXPORT_DEFAULT
#endif

PANDAR_IGNORE_CXX_LINKAGE_BEGIN

PANDAR_STUDIO_EXPORT(bambu_network_check_debug_consistent, func_check_debug_consistent, bool, (bool))
PANDAR_STUDIO_EXPORT(bambu_network_get_version, func_get_version, std::string, (void))
PANDAR_STUDIO_EXPORT(bambu_network_create_agent, func_create_agent, void*, (std::string))
PANDAR_STUDIO_EXPORT(bambu_network_destroy_agent, func_destroy_agent, int, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_init_log, func_init_log, int, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_set_config_dir, func_set_config_dir, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_set_cert_file, func_set_cert_file, int, (void*, std::string, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_set_country_code, func_set_country_code, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_start, func_start, int, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_ssdp_msg_fn, func_set_on_ssdp_msg_fn, int, (void*, BBL::OnMsgArrivedFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_user_login_fn, func_set_on_user_login_fn, int, (void*, BBL::OnUserLoginFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_printer_connected_fn, func_set_on_printer_connected_fn, int, (void*, BBL::OnPrinterConnectedFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_server_connected_fn, func_set_on_server_connected_fn, int, (void*, BBL::OnServerConnectedFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_http_error_fn, func_set_on_http_error_fn, int, (void*, BBL::OnHttpErrorFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_get_country_code_fn, func_set_get_country_code_fn, int, (void*, BBL::GetCountryCodeFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_subscribe_failure_fn, func_set_on_subscribe_failure_fn, int, (void*, BBL::GetSubscribeFailureFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_message_fn, func_set_on_message_fn, int, (void*, BBL::OnMessageFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_user_message_fn, func_set_on_user_message_fn, int, (void*, BBL::OnMessageFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_local_connect_fn, func_set_on_local_connect_fn, int, (void*, BBL::OnLocalConnectedFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_on_local_message_fn, func_set_on_local_message_fn, int, (void*, BBL::OnMessageFn))
PANDAR_STUDIO_EXPORT(bambu_network_set_queue_on_main_fn, func_set_queue_on_main_fn, int, (void*, BBL::QueueOnMainFn))
PANDAR_STUDIO_EXPORT(bambu_network_connect_server, func_connect_server, int, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_is_server_connected, func_is_server_connected, bool, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_refresh_connection, func_refresh_connection, int, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_start_subscribe, func_start_subscribe, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_stop_subscribe, func_stop_subscribe, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_add_subscribe, func_add_subscribe, int, (void*, std::vector<std::string>))
PANDAR_STUDIO_EXPORT(bambu_network_del_subscribe, func_del_subscribe, int, (void*, std::vector<std::string>))
PANDAR_STUDIO_EXPORT(bambu_network_enable_multi_machine, func_enable_multi_machine, void, (void*, bool))
PANDAR_STUDIO_EXPORT(bambu_network_send_message, func_send_message, int, (void*, std::string, std::string, int, int))
PANDAR_STUDIO_EXPORT(bambu_network_connect_printer, func_connect_printer, int, (void*, std::string, std::string, std::string, std::string, bool))
PANDAR_STUDIO_EXPORT(bambu_network_disconnect_printer, func_disconnect_printer, int, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_send_message_to_printer, func_send_message_to_printer, int, (void*, std::string, std::string, int, int))
PANDAR_STUDIO_EXPORT(bambu_network_update_cert, func_check_cert, int, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_install_device_cert, func_install_device_cert, void, (void*, std::string, bool))
PANDAR_STUDIO_EXPORT(bambu_network_start_discovery, func_start_discovery, bool, (void*, bool, bool))
PANDAR_STUDIO_EXPORT(bambu_network_change_user, func_change_user, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_is_user_login, func_is_user_login, bool, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_user_logout, func_user_logout, int, (void*, bool))
PANDAR_STUDIO_EXPORT(bambu_network_get_user_id, func_get_user_id, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_get_user_name, func_get_user_name, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_get_user_avatar, func_get_user_avatar, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_get_user_nickanme, func_get_user_nickanme, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_build_login_cmd, func_build_login_cmd, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_build_logout_cmd, func_build_logout_cmd, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_build_login_info, func_build_login_info, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_ping_bind, func_ping_bind, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_bind_detect, func_bind_detect, int, (void*, std::string, std::string, BBL::detectResult&))
PANDAR_STUDIO_EXPORT(bambu_network_report_consent, func_report_consent, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_set_server_callback, func_set_server_callback, int, (void*, BBL::OnServerErrFn))
PANDAR_STUDIO_EXPORT(bambu_network_bind, func_bind, int, (void*, std::string, std::string, std::string, std::string, PANDAR_STUDIO_BIND_MODEL_PARAMETER bool, BBL::OnUpdateStatusFn))
PANDAR_STUDIO_EXPORT(bambu_network_unbind, func_unbind, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_get_bambulab_host, func_get_bambulab_host, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_get_user_selected_machine, func_get_user_selected_machine, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_set_user_selected_machine, func_set_user_selected_machine, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_start_print, func_start_print, int, (void*, BBL::PrintParams, BBL::OnUpdateStatusFn, BBL::WasCancelledFn, BBL::OnWaitFn))
PANDAR_STUDIO_EXPORT(bambu_network_start_local_print_with_record, func_start_local_print_with_record, int, (void*, BBL::PrintParams, BBL::OnUpdateStatusFn, BBL::WasCancelledFn, BBL::OnWaitFn))
PANDAR_STUDIO_EXPORT(bambu_network_start_send_gcode_to_sdcard, func_start_send_gcode_to_sdcard, int, (void*, BBL::PrintParams, BBL::OnUpdateStatusFn, BBL::WasCancelledFn, BBL::OnWaitFn))
PANDAR_STUDIO_EXPORT(bambu_network_start_local_print, func_start_local_print, int, (void*, BBL::PrintParams, BBL::OnUpdateStatusFn, BBL::WasCancelledFn))
PANDAR_STUDIO_EXPORT(bambu_network_start_sdcard_print, func_start_sdcard_print, int, (void*, BBL::PrintParams, BBL::OnUpdateStatusFn, BBL::WasCancelledFn))
PANDAR_STUDIO_EXPORT(bambu_network_get_user_presets, func_get_user_presets, int, (void*, std::map<std::string, std::map<std::string, std::string>>*))
PANDAR_STUDIO_EXPORT(bambu_network_request_setting_id, func_request_setting_id, std::string, (void*, std::string, std::map<std::string, std::string>*, unsigned int*))
PANDAR_STUDIO_EXPORT(bambu_network_put_setting, func_put_setting, int, (void*, std::string, std::string, std::map<std::string, std::string>*, unsigned int*))
PANDAR_STUDIO_EXPORT(bambu_network_get_setting_list, func_get_setting_list, int, (void*, std::string, BBL::ProgressFn, BBL::WasCancelledFn))
PANDAR_STUDIO_EXPORT(bambu_network_get_setting_list2, func_get_setting_list2, int, (void*, std::string, BBL::CheckFn, BBL::ProgressFn, BBL::WasCancelledFn))
PANDAR_STUDIO_EXPORT(bambu_network_delete_setting, func_delete_setting, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_get_studio_info_url, func_get_studio_info_url, std::string, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_set_extra_http_header, func_set_extra_http_header, int, (void*, std::map<std::string, std::string>))
PANDAR_STUDIO_EXPORT(bambu_network_get_my_message, func_get_my_message, int, (void*, int, int, int, unsigned int*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_check_user_task_report, func_check_user_task_report, int, (void*, int*, bool*))
PANDAR_STUDIO_EXPORT(bambu_network_get_user_print_info, func_get_user_print_info, int, (void*, unsigned int*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_get_user_tasks, func_get_user_tasks, int, (void*, BBL::TaskQueryParams, std::string*))
#if defined(PANDAR_STUDIO_FILAMENT_CLOUD)
PANDAR_STUDIO_EXPORT(bambu_network_get_filament_spools, func_get_filament_spools, int, (void*, BBL::FilamentQueryParams, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_create_filament_spool, func_create_filament_spool, int, (void*, std::string, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_update_filament_spool, func_update_filament_spool, int, (void*, std::string, std::string, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_delete_filament_spools, func_delete_filament_spools, int, (void*, BBL::FilamentDeleteParams, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_get_filament_config, func_get_filament_config, int, (void*, std::string*))
#endif
PANDAR_STUDIO_EXPORT(bambu_network_get_printer_firmware, func_get_printer_firmware, int, (void*, std::string, unsigned*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_get_task_plate_index, func_get_task_plate_index, int, (void*, std::string, int*))
PANDAR_STUDIO_EXPORT(bambu_network_get_user_info, func_get_user_info, int, (void*, int*))
PANDAR_STUDIO_EXPORT(bambu_network_request_bind_ticket, func_request_bind_ticket, int, (void*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_get_subtask_info, func_get_subtask_info, int, (void*, std::string, std::string*, unsigned int*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_get_slice_info, func_get_slice_info, int, (void*, std::string, std::string, int, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_query_bind_status, func_query_bind_status, int, (void*, std::vector<std::string>, unsigned int*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_modify_printer_name, func_modify_printer_name, int, (void*, std::string, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_get_camera_url, func_get_camera_url, int, (void*, std::string, std::function<void(std::string)>))
PANDAR_STUDIO_EXPORT(bambu_network_get_camera_url_for_golive, func_get_camera_url_for_golive, int, (void*, std::string, std::string, std::function<void(std::string)>))
PANDAR_STUDIO_EXPORT(bambu_network_get_design_staffpick, func_get_design_staffpick, int, (void*, int, int, std::function<void(std::string)>))
PANDAR_STUDIO_EXPORT(bambu_network_start_publish, func_start_pubilsh, int, (void*, BBL::PublishParams, BBL::OnUpdateStatusFn, BBL::WasCancelledFn, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_get_model_publish_url, func_get_model_publish_url, int, (void*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_get_subtask, func_get_subtask, int, (void*, Slic3r::BBLModelTask*, std::function<void(Slic3r::BBLModelTask*)>))
PANDAR_STUDIO_EXPORT(bambu_network_get_model_mall_home_url, func_get_model_mall_home_url, int, (void*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_get_model_mall_detail_url, func_get_model_mall_detail_url, int, (void*, std::string*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_get_my_profile, func_get_my_profile, int, (void*, std::string, unsigned int*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_get_my_token, func_get_my_profile, int, (void*, std::string, unsigned int*, std::string*))
PANDAR_STUDIO_EXPORT(bambu_network_track_enable, func_track_enable, int, (void*, bool))
PANDAR_STUDIO_EXPORT(bambu_network_track_remove_files, func_track_remove_files, int, (void*))
PANDAR_STUDIO_EXPORT(bambu_network_track_event, func_track_event, int, (void*, std::string, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_track_header, func_track_header, int, (void*, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_track_update_property, func_track_update_property, int, (void*, std::string, std::string, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_track_get_property, func_track_get_property, int, (void*, std::string, std::string&, std::string))
PANDAR_STUDIO_EXPORT(bambu_network_put_model_mall_rating, func_put_model_mall_rating_url, int, (void*, int, int, std::string, std::vector<std::string>, unsigned int&, std::string&))
PANDAR_STUDIO_EXPORT(bambu_network_get_oss_config, func_get_oss_config, int, (void*, std::string&, std::string, unsigned int&, std::string&))
PANDAR_STUDIO_EXPORT(bambu_network_put_rating_picture_oss, func_put_rating_picture_oss, int, (void*, std::string&, std::string&, std::string, int, unsigned int&, std::string&))
PANDAR_STUDIO_EXPORT(bambu_network_get_model_mall_rating, func_get_model_mall_rating_result, int, (void*, int, std::string&, unsigned int&, std::string&))
PANDAR_STUDIO_EXPORT(bambu_network_get_mw_user_preference, func_get_mw_user_preference, int, (void*, std::function<void(std::string)>))
PANDAR_STUDIO_EXPORT(bambu_network_get_mw_user_4ulist, func_get_mw_user_4ulist, int, (void*, int, int, std::function<void(std::string)>))
PANDAR_STUDIO_EXPORT(bambu_network_get_hms_snapshot, func_get_hms_snapshot, int, (void*, std::string&, std::string&, std::function<void(std::string, int)>))
#if defined(PANDAR_STUDIO_AMS_SYNC)
PANDAR_STUDIO_EXPORT(bambu_network_sync_ams_filaments, func_sync_ams_filaments, int, (void*, BBL::AmsSyncParams, std::string*))
#endif
PANDAR_STUDIO_EXPORT(ft_abi_version, fn_ft_abi_version, int, ())
PANDAR_STUDIO_EXPORT(ft_free, fn_ft_free, void, (void*))
PANDAR_STUDIO_EXPORT(ft_job_result_destroy, fn_ft_job_result_destroy, void, (Slic3r::ft_job_result*))
PANDAR_STUDIO_EXPORT(ft_job_msg_destroy, fn_ft_job_msg_destroy, void, (Slic3r::ft_job_msg*))
PANDAR_STUDIO_EXPORT(ft_tunnel_create, fn_ft_tunnel_create, Slic3r::ft_err, (const char*, Slic3r::FT_TunnelHandle**))
PANDAR_STUDIO_EXPORT(ft_tunnel_retain, fn_ft_tunnel_retain, void, (Slic3r::FT_TunnelHandle*))
PANDAR_STUDIO_EXPORT(ft_tunnel_release, fn_ft_tunnel_release, void, (Slic3r::FT_TunnelHandle*))
PANDAR_STUDIO_EXPORT(ft_tunnel_start_connect, fn_ft_tunnel_start_connect, Slic3r::ft_err, (Slic3r::FT_TunnelHandle*, void(PANDAR_STUDIO_FT_CALL*)(void*, int, int, const char*), void*))
PANDAR_STUDIO_EXPORT(ft_tunnel_sync_connect, fn_ft_tunnel_sync_connect, Slic3r::ft_err, (Slic3r::FT_TunnelHandle*))
PANDAR_STUDIO_EXPORT(ft_tunnel_set_status_cb, fn_ft_tunnel_set_status_cb, Slic3r::ft_err, (Slic3r::FT_TunnelHandle*, void(PANDAR_STUDIO_FT_CALL*)(void*, int, int, int, const char*), void*))
PANDAR_STUDIO_EXPORT(ft_tunnel_shutdown, fn_ft_tunnel_shutdown, Slic3r::ft_err, (Slic3r::FT_TunnelHandle*))
PANDAR_STUDIO_EXPORT(ft_job_create, fn_ft_job_create, Slic3r::ft_err, (const char*, Slic3r::FT_JobHandle**))
PANDAR_STUDIO_EXPORT(ft_job_retain, fn_ft_job_retain, void, (Slic3r::FT_JobHandle*))
PANDAR_STUDIO_EXPORT(ft_job_release, fn_ft_job_release, void, (Slic3r::FT_JobHandle*))
PANDAR_STUDIO_EXPORT(ft_job_set_result_cb, fn_ft_job_set_result_cb, Slic3r::ft_err, (Slic3r::FT_JobHandle*, void(PANDAR_STUDIO_FT_CALL*)(void*, Slic3r::ft_job_result), void*))
PANDAR_STUDIO_EXPORT(ft_job_get_result, fn_ft_job_get_result, Slic3r::ft_err, (Slic3r::FT_JobHandle*, uint32_t, Slic3r::ft_job_result*))
PANDAR_STUDIO_EXPORT(ft_tunnel_start_job, fn_ft_tunnel_start_job, Slic3r::ft_err, (Slic3r::FT_TunnelHandle*, Slic3r::FT_JobHandle*))
PANDAR_STUDIO_EXPORT(ft_job_cancel, fn_ft_job_cancel, Slic3r::ft_err, (Slic3r::FT_JobHandle*))
PANDAR_STUDIO_EXPORT(ft_job_set_msg_cb, fn_ft_job_set_msg_cb, Slic3r::ft_err, (Slic3r::FT_JobHandle*, void(PANDAR_STUDIO_FT_CALL*)(void*, Slic3r::ft_job_msg), void*))
PANDAR_STUDIO_EXPORT(ft_job_try_get_msg, fn_ft_job_try_get_msg, Slic3r::ft_err, (Slic3r::FT_JobHandle*, Slic3r::ft_job_msg*))
PANDAR_STUDIO_EXPORT(ft_job_get_msg, fn_ft_job_get_msg, Slic3r::ft_err, (Slic3r::FT_JobHandle*, uint32_t, Slic3r::ft_job_msg*))

PANDAR_IGNORE_CXX_LINKAGE_END

#ifdef PANDAR_STUDIO_EXPORT_DEFAULT
#undef PANDAR_STUDIO_EXPORT_DEFAULT
#undef PANDAR_STUDIO_EXPORT
#endif

#undef PANDAR_STUDIO_FT_CALL
