[package]
name = "pandar-network-plugin"
version = "0.1.3"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
cc = "1.2.47"
pandar-studio-profile.workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
http-body.workspace = true
http-body-util.workspace = true
pandar-core.workspace = true
pandar-studio-profile.workspace = true
quick-xml.workspace = true
reqwest.workspace = true
rust-embed.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-util.workspace = true
zip.workspace = true

[dev-dependencies]
cc = "1.2.47"
tempfile.workspace = true
