[package]
name = "pandar-agent"
version = "0.1.4"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
aws-lc-rs.workspace = true
base64.workspace = true
cap-std.workspace = true
clap.workspace = true
futures-util.workspace = true
if-addrs.workspace = true
md-5.workspace = true
pandar-core.workspace = true
prost.workspace = true
reqwest.workspace = true
rumqttc.workspace = true

rustls.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
sha2.workspace = true
suppaftp.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-stream.workspace = true
tonic = { workspace = true, features = ["tls-aws-lc", "tls-native-roots"] }
tonic-prost.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
x509-parser = { workspace = true, features = ["verify-aws"] }

[build-dependencies]
protoc-bin-vendored.workspace = true
tonic-prost-build.workspace = true

[dev-dependencies]
clap.workspace = true
rcgen.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
tracing-core.workspace = true
